"""Fix: Add Price Column to Restaurant Model

Revision ID: e0547058cd07
Revises: fef9a30dfb72
Create Date: 2023-09-04 01:00:05.649348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0547058cd07'
down_revision: Union[str, None] = 'fef9a30dfb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_index('ix_restaurants_name', table_name='restaurants')
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.create_index('ix_restaurants_name', 'restaurants', ['name'], unique=False)
    op.drop_column('restaurants', 'price')
    # ### end Alembic commands ###
